
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_DNN(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);
/*
	This Code is done for synthesis not a functional code
*/


//=======================================================
//  REG/WIRE declarations
//=======================================================
	wire clk;
    wire [7:0] in_address;
    wire [7:0] out_feature;
    wire [3:0] out_address;
	wire locked;
//=======================================================
//  Structural coding
//=======================================================
 PLL u_PLL(
		.refclk(CLOCK_50),   //  refclk.clk
		.rst(KEY[0]),      //   reset.reset
		.outclk_0(clk)  // outclk0.clk
	);

DNN #(
    .NUM_INPUT(84),
    .NUM_OUTPUT(10),
    .OUT_FORMAT("Q1_7"),
    .WEIGHT_FILE("rtl/dense3_weight.mem"),
    .BIAS_FILE("rtl/dense3_bias.mem")
) u_DNN (
    .clk(clk),
	.rst(KEY[0]), 
    // Input Features bus
    .in_feature('h78),
    .in_address(in_address),
    .in_start(KEY[1]),
    // Output Features bus
    .out_feature(out_feature),
    .out_address(out_address),
    .out_enable(LEDR[0]),
    .out_done(LEDR[1])
);

seven_segment_display u0(    
    .BIN(out_address),
	.HEX(HEX0)
);

seven_segment_display u1(    
    .BIN(out_feature[3:0]),
	.HEX(HEX1)
);

seven_segment_display u2(    
    .BIN(out_feature[7:4]),
	.HEX(HEX2)
);

seven_segment_display u3(    
    .BIN(in_address[3:0]),
	.HEX(HEX3)
);

seven_segment_display u4(    
    .BIN(in_address[7:4]),
	.HEX(HEX4)
);
endmodule
