
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module HPS_FPGA_Top(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// HPS //////////
	inout 		          		HPS_CONV_USB_N,
	output		    [14:0]		HPS_DDR3_ADDR,
	output		     [2:0]		HPS_DDR3_BA,
	output		          		HPS_DDR3_CAS_N,
	output		          		HPS_DDR3_CKE,
	output		          		HPS_DDR3_CK_N,
	output		          		HPS_DDR3_CK_P,
	output		          		HPS_DDR3_CS_N,
	output		     [3:0]		HPS_DDR3_DM,
	inout 		    [31:0]		HPS_DDR3_DQ,
	inout 		     [3:0]		HPS_DDR3_DQS_N,
	inout 		     [3:0]		HPS_DDR3_DQS_P,
	output		          		HPS_DDR3_ODT,
	output		          		HPS_DDR3_RAS_N,
	output		          		HPS_DDR3_RESET_N,
	input 		          		HPS_DDR3_RZQ,
	output		          		HPS_DDR3_WE_N,
	output		          		HPS_ENET_GTX_CLK,
	inout 		          		HPS_ENET_INT_N,
	output		          		HPS_ENET_MDC,
	inout 		          		HPS_ENET_MDIO,
	input 		          		HPS_ENET_RX_CLK,
	input 		     [3:0]		HPS_ENET_RX_DATA,
	input 		          		HPS_ENET_RX_DV,
	output		     [3:0]		HPS_ENET_TX_DATA,
	output		          		HPS_ENET_TX_EN,
	inout 		     [3:0]		HPS_FLASH_DATA,
	output		          		HPS_FLASH_DCLK,
	output		          		HPS_FLASH_NCSO,
	inout 		     [1:0]		HPS_GPIO,
	inout 		          		HPS_GSENSOR_INT,
	inout 		          		HPS_I2C1_SCLK,
	inout 		          		HPS_I2C1_SDAT,
	inout 		          		HPS_I2C2_SCLK,
	inout 		          		HPS_I2C2_SDAT,
	inout 		          		HPS_I2C_CONTROL,
	inout 		          		HPS_KEY,
	inout 		          		HPS_LED,
	output		          		HPS_SD_CLK,
	inout 		          		HPS_SD_CMD,
	inout 		     [3:0]		HPS_SD_DATA,
	output		          		HPS_SPIM_CLK,
	input 		          		HPS_SPIM_MISO,
	output		          		HPS_SPIM_MOSI,
	inout 		          		HPS_SPIM_SS,
	input 		          		HPS_UART_RX,
	output		          		HPS_UART_TX,
	input 		          		HPS_USB_CLKOUT,
	inout 		     [7:0]		HPS_USB_DATA,
	input 		          		HPS_USB_DIR,
	input 		          		HPS_USB_NXT,
	output		          		HPS_USB_STP
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	// Clock
		wire clk;
	// Input Interface 
	    wire LeNet_write_enable_sync;
	    wire LeNet_start_sync;
		wire [7:0] LeNet_write_addr; 
		wire [7:0] LeNet_data_in;
		wire       LeNet_write_enable;
		wire       LeNet_start;
	// Output Predication 
		wire [9:0] out_argmax_prediction;
		wire out_valid;



//=======================================================
//  Structural coding
//=======================================================
	// pll u3(
	// 	.refclk(CLOCK_50),   //  refclk.clk
	// 	.rst(1'b0),      //   reset.reset
	// 	.outclk_0(clk)  // outclk0.clk
	// );

	assign clk = CLOCK_50;
    computer_system u0 (
        .clk_clk             (clk),             //          clk.clk
        .reset_reset_n       (1'b1),      			  //        reset.reset_n
		  // HPS DDR3 Memory
        .memory_mem_a        (HPS_DDR3_ADDR),        
        .memory_mem_ba       (HPS_DDR3_BA),       
        .memory_mem_ck       (HPS_DDR3_CK_P),       
        .memory_mem_ck_n     (HPS_DDR3_CK_N),     
        .memory_mem_cke      (HPS_DDR3_CKE),      
        .memory_mem_cs_n     (HPS_DDR3_CS_N),     
        .memory_mem_ras_n    (HPS_DDR3_RAS_N),    
        .memory_mem_cas_n    (HPS_DDR3_CAS_N),    
        .memory_mem_we_n     (HPS_DDR3_WE_N),     
        .memory_mem_reset_n  (HPS_DDR3_RESET_N),  
        .memory_mem_dq       (HPS_DDR3_DQ),       
        .memory_mem_dqs      (HPS_DDR3_DQS_P),      
        .memory_mem_dqs_n    (HPS_DDR3_DQS_N),    
        .memory_mem_odt      (HPS_DDR3_ODT),      
        .memory_mem_dm       (HPS_DDR3_DM),       
        .memory_oct_rzqin    (HPS_DDR3_RZQ),
		 // System Interface 
        .lenet_addr_export(LeNet_write_addr),
		.lenet_data_export(LeNet_data_in),
		.lenet_write_enable_export(LeNet_write_enable),
		.lenet_start_export(LeNet_start),
		.lenet_predication_out_export(out_argmax_prediction),
		.lenet_predication_valid_export(out_valid)
	);

	LeNet5 u1 (
		.clk(clk),
		.rst(1'b0),
		// Input Interface 
		.LeNet_write_addr(LeNet_write_addr), 
		.LeNet_data_in(LeNet_data_in),
		.LeNet_write_enable(LeNet_write_enable_sync), // Clean signal
        .LeNet_start(LeNet_start_sync),               // Clean signal
		// Output Predication 
		.out_argmax_prediction(out_argmax_prediction),
		.out_valid(out_valid)
	);

	assign LEDR = out_argmax_prediction;

    // Synchronize Write Enable
    sync_2ff sync_wen (
        .clk(clk),
        .rst(1'b0), // Or your actual reset wire
        .async_in(LeNet_write_enable),
        .sync_out(LeNet_write_enable_sync)
    );

    // Synchronize Start Signal
    sync_2ff sync_start (
        .clk(clk),
        .rst(1'b0),
        .async_in(LeNet_start),
        .sync_out(LeNet_start_sync)
    );

endmodule
