
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_OutLayer(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

// This Code is only for Synthesis and it's not functional

//=======================================================
//  REG/WIRE declarations
//=======================================================


//=======================================================
//  Structural coding
//=======================================================

Output_Layer(
    .clk(CLOCK_50),
    .rst(KEY[0]),
    // Input Features
    .in_feature({SW[6:0],1'b0}),
    .in_address(SW[9:7]), 
    .in_enable(KEY[1]),
    .in_start(KEY[2]), 
    // Output Prediction 
    .prediction(LEDR)
);

endmodule
